apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: my-argocd-helm-app
  namespace: argocd
spec:
  project: default
  source:
    chart: my-argocd-helm-app
    repoURL: https://gitlab.com/general23/my-manifest-repo.git
    targetRevision: 1.16.1
    helm:
      releaseName: my-argocd-helm-app
  destination:
    server: "https://kubernetes.default.svc"
    namespace: argocd-dev

